CREATE TABLE IF NOT EXISTS movies (
  movie_id VARCHAR(26) PRIMARY KEY,
  uuid UUID UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  release_date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 