CREATE TABLE IF NOT EXISTS actors (
  actor_id VARCHAR(26) PRIMARY KEY,
  uuid UUID UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  birth_date DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 